# Generated by Django 4.2.27 on 2026-02-12

from __future__ import annotations

from decimal import Decimal

from django.db import migrations


def forwards(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Debt = apps.get_model("credits", "Debt")

    # Create debts for any order with a customer and without an existing debt.
    # This enables "en deuda" for contado/transferencia too (until negocio marks paid).
    existing_order_ids = set(Debt.objects.values_list("order_id", flat=True))
    qs = (
        Order.objects.exclude(customer_id__isnull=True)
        .exclude(id__in=existing_order_ids)
        .only("id", "restaurant_id", "customer_id", "total")
    )
    for o in qs.iterator():
        Debt.objects.create(
            restaurant_id=o.restaurant_id,
            customer_id=o.customer_id,
            order_id=o.id,
            status="OPEN",
            amount_original=o.total or Decimal("0.00"),
            amount_paid=Decimal("0.00"),
        )


def backwards(apps, schema_editor):
    # No-op: we don't delete generated debts.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0004_customer_address"),
        ("orders", "0004_order_customer_note"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards, elidable=True),
    ]

