# Generated by Django 4.2.27 on 2026-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_normalize_userprofile_phones_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='restaurantmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='restaurantmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SAAS_ADMIN', 'Administrador SaaS'), ('RESTAURANT_ADMIN', 'Administrador del restaurante')], max_length=32),
        ),
    ]
