# Generated by Django 4.2.27 on 2026-03-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SAAS_ADMIN', 'Administrador SaaS'), ('RESTAURANT_ADMIN', 'Administrador del restaurante'), ('CUSTOMER', 'Cliente')], max_length=32),
        ),
    ]
