# Generated by Django 4.2.27 on 2026-02-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menus/%Y/%m/%d/'),
        ),
    ]
