# Generated by Django 4.2.27 on 2026-02-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_dailymenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
