# Generated by Django 4.2.27 on 2026-02-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_dailymenu_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='title',
            field=models.CharField(default='Menú del día', max_length=120),
        ),
    ]
