# Generated by Django 4.2.27 on 2026-02-12

from __future__ import annotations

from datetime import datetime, time, timedelta

from django.db import migrations, models
from django.utils import timezone


def forwards_set_visible_until(apps, schema_editor):
    DailyMenu = apps.get_model("menus", "DailyMenu")
    tz = timezone.get_current_timezone()
    qs = DailyMenu.objects.filter(is_visible=True, visible_until__isnull=True)
    for m in qs.iterator():
        # Por compatibilidad con menús viejos: si estaba visible, dejarlo visible
        # hasta el inicio del día siguiente a su "date".
        naive = datetime.combine(m.date + timedelta(days=1), time.min)
        m.visible_until = timezone.make_aware(naive, tz)
        m.save(update_fields=["visible_until"])


def backwards_unset_visible_until(apps, schema_editor):
    DailyMenu = apps.get_model("menus", "DailyMenu")
    DailyMenu.objects.all().update(visible_until=None)


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0004_dailymenu_description_dailymenu_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymenu",
            name="visible_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Si está visible, se ocultará automáticamente al pasar esta fecha/hora.",
                null=True,
            ),
        ),
        migrations.RunPython(
            forwards_set_visible_until, backwards_unset_visible_until, elidable=True
        ),
    ]

