# Generated by Django 4.2.27 on 2026-02-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_dailymenu_visible_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenuitem',
            options={'ordering': ['item__name']},
        ),
        migrations.RemoveField(
            model_name='dailymenuitem',
            name='available',
        ),
        migrations.RemoveField(
            model_name='dailymenuitem',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=16),
        ),
    ]
