# Generated by Django 4.2.27 on 2026-02-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_full_menu',
            field=models.BooleanField(default=False, help_text='Si el cliente compró el menú completo (bandeja y sopa).'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Contado'), ('CREDIT', 'Crédito'), ('TRANSFER', 'Transferencia')], max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=16),
        ),
    ]
