# Generated by Django 4.2.27 on 2026-02-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_full_menu_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.CharField(blank=True, help_text='Mensaje opcional del cliente para el negocio.', max_length=255),
        ),
    ]
